server:
  port: 8080
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    mongodb:
      database: banco
      host: localhost
      port: 27017
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
